/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 12-oct.-2021 8:28:58 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[tblEstacionCarga]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [tblEstacionCarga]
GO

/* Create Tables */

CREATE TABLE [tblEstacionCarga]
(
	[intIdEstacionCarga] int NOT NULL IDENTITY (1, 1),
	[strNombre] nvarchar(max) NULL,
	[numLatitud] numeric(18,14) NULL,
	[numLongitud] numeric(18,14) NULL,
	[blnActivo] bit NULL DEFAULT 1,
	[dtmActualiza] datetime NULL DEFAULT GETDATE()
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [tblEstacionCarga] 
 ADD CONSTRAINT [PK_tblEstacion]
	PRIMARY KEY CLUSTERED ([intIdEstacionCarga] ASC)
GO
